### ISSUE TITLE
Error description:AADSTS50079: The user is required to use multi-factor authentication.

### ISSUE THREAD

**Issue by zmyvszk** [Azure-Samples/active-directory-angularjs-singlepageapp#41]
I have this problem when calling MS Graph on Chrome, but it's working fine for IE and Edge. I did every configuration stuff according to the document. Is there any problem? Thanks!

**Comment by jmprieur** [comment]
I believe that this was working in IE and Edge, because you were already logged-in in these browsers or in Windows, and had already done the multi-factor authentication for some web apps.
Until ADAL.js 1.0.15, this was not possible to handle multi-factor authentication after login.
https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp/pull/43, integrating ADAL.js 1.0.15 brings this capability. Closing this issues. feel free to re-open if this still reproes (but please with repro steps)
