### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by cognologixguru** [Azure-Samples/active-directory-angularjs-singlepageapp#44]
Additional technical information:
Correlation ID: c2423490-3795-4097-9100-c8a6d0fabcc8
Timestamp: 2017-08-23 19:17:29Z
AADSTS70001: Application with identifier '0abb4c32-97b5-432b-a6ea-42ca08be' was not found in the directory ********.onmicrosoft.com

**Comment by jmprieur** [comment]
Hell @cognologixguru.
Did you register you app with the Azure portal (https://portal.azure.com/) as explained in the README.md of this sample? 

Or would you by any chance have registered it with the Application Registration Portal (https://apps.dev.microsoft.com), where you would have added a converged application?
If this is the later, then the error is expected because the Application Registration Portal is used to add applications for the Azure AD V2 endpoint (applications that can be accessed both by Work/School accounts and Microsoft personal accounts), whereas this sample uses adal.js which only supports the V1 endpoint (only Work/School accounts and on premise Active Directory (ADFS)). 
You need to register your application with the Azure portal  (https://portal.azure.com/)

**Comment by cognologixguru** [comment]
Hello @jmprieur ,
Thank you for reply. I will try as per your suggestion and I will inform you if any any issue persists.

**Comment by jmprieur** [comment]
Closing for now. Feel free to re-open if this does not work for you.
